### ISSUE TITLE
About utils.py

### ISSUE THREAD

**Issue by Pasxsenger** [BIT-DA/SSAN#1]
Hi,
I appreciate your excellent work. And I am trying to learn from that.
I noticed the"os.environ['PYTHONASHSEED'] = str(args.seed)" in line 16 of utils.py. I searched "PYTHONASHSEED" but got no result but "PYTHONHASHSEED", which has an "H" between the "N" and "A".
So, I think maybe it should be "PYTHONHASHSEED".

**Comment by BinhuiXie** [comment]
Hello @Pasxsenger,

Thanks a lot. It was a spelling mistake.😂

**Comment by Pasxsenger** [comment]
I guess so. 😄
