### ISSUE TITLE
Code for SGW

### ISSUE THREAD

**Issue by XJTU-XGU** [BIT-DA/SSAN#2]
Dear author,

I found you have reported the results of SGW method in the paper. However, I can not find the code of SGW. Could you please offer some help? 

Thank you very much!

Best wishes

**Comment by BinhuiXie** [comment]
Hi, @XJTU-XGU 

Thank you for your attention to our work.

Actually, the results of SGW are directly copied from [STN](https://arxiv.org/pdf/1908.10552.pdf). I’m sorry I’m not able to help you at this time.

**Comment by XJTU-XGU** [comment]
Thank you very much for the reply！
